###############
## 
####


GPU: [0]

VERBOSE: True

MODEL:
  MODE: 'Deraining'
  SESSION: 'CRFamba'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 4
  NUM_EPOCHS: 950
  NEPOCH_DECAY: [10]
  LR_INITIAL: 1e-5  #
  LR_MIN: 1e-6
  BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 256
  VAL_PS: 256
  TRAIN_DIR: './T-Cloud/train' # path to training data
  VAL_DIR: './T-Cloud/test'    # path to validation data
  SAVE_DIR: './checkpoints_tcloud'     # path to save models and images
  # SAVE_IMAGES: False
